### ISSUE TITLE
Forholdet til NVDB (avsnitt 2.1 m.fl.)

### ISSUE THREAD

**Issue by sovde** [jetgeo/SOSI-Vegnett#24]
I avsnitt 2.1 nevnes det at NVDB inngår i SOSI-modellregister. Dette innebærer ikke at NVDB inngår i SOSI-standarden. Det er ikke avklart hvilken plass NVDB skal ha i SOSI-standarden. Det er derfor uheldig at fagområdestandarden har avhengighet til NVDB.

I dagens situasjon er det mest naturlig at pakkene flyttes til Vegnett 4.6. Framtidige versjoner av NVDB bør deretter oppdateres med avhengighet til Vegnett 4.6.

**Comment by jetgeo** [comment]
Det er avklart hvilken plass NVDB skal ha i SOSI-standarden: Den skal ikke være en del av den. Men modellene skal inngå i SOSI-modellregister, og en del objekttyper skal også harmoniseres med SOSI-standarder. 
Det er ikke naturlig å ta deler av NVDB inn i standarden, dette har vi diskutert og konkludert for tidligere. NVDB Datakatalogen kommer i nye versjoner 4 ganger i året, og det er ikke hensiktsmessig å revidere SOSI-standarder så ofte. En ren standard for vegnett gir også en mye enklere og ryddigere standard, mens objekttyper som skal knyttes til vegnettet forvaltes andre steder. Det sentrale for bruken i produktspesifikasjoner er at de er tilgjengelige i SOSI-modellregister. 
Den eneste avhengigheten til NVDB fra standarden er kodelistene for vegkategori og vegstatus. Tilsvarende avhengigheter vil det være naturlig å ha for andre kodelister i andre standarder, for eksempel kommunenummer, arter mm. Disse listene forvaltes utenfor standarden, og kan dermed være mer dynamiske.
