### ISSUE TITLE
3.2 Målsetting og 3.3 Bruksområde

### ISSUE THREAD

**Issue by sovde** [jetgeo/SOSI-Vegnett#25]
Avsnitt 3.2 og 3.3 er motivasjon for produktspesifikasjoner. Målsetting og bruksområde for en fagområdestandard er videre:

- En fagområdestandard skal harmonisere geodata. Ulike produktspesifikasjoner bør benytte identiske objekttyper der det er mulig.
- En fagområdestandard har vært gjennom en prosess som øker kvaliteten på dokumentasjon (og kanskje også på geodataene).

I tillegg er det kanskje underforstått at økning i anvendelsesområder også vil føre til en økning i antall produktspesifikasjoner?

**Comment by jetgeo** [comment]
Har prøvd å justere teksten i henhold til dette.
