### ISSUE TITLE
Figurtekst med referanse til avsnitt

### ISSUE THREAD

**Issue by sovde** [jetgeo/SOSI-Vegnett#28]
Figurteksten til Figur 11 (m.fl?) har henvisning til 'neste kapittel'. Det er vel ikke noen regler for figurer i SOSI-standarden. Et utgangspunkt kan være at figurteksten skal forklare figuren, og det gjør den ikke hvis det vises til avsnitt i dokumentet. Er det mulig å fjerne kolonnene 'Detaljeringsnivå' og 'Konnekteringslenke' i Figur 11? Detaljeringsnivå er uansett ikke forklart.

Hvis referansen til 'neste delkapittel' beholdes bør avsnittsnummer spesifiseres.

**Comment by jetgeo** [comment]
Detaljnivå er forklart i kap. 6.3.2.2. Kolonnene for detaljnivå og konnekteringslenke er viktige for figuren - typeveg, detaljnivå og konnekteringslenke utgjør en sammenheng. Teksten under figurteksten kan flyttes ut i selve dokumentet, der må det være greit med henvisning til forklaringer andre steder i dokumentet. 
Ref også https://github.com/jetgeo/SOSI-Vegnett/issues/27
